sudo: false

language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules

before_install:
  - npm i coveralls

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - develop
